<a href="https://colab.research.google.com/github/emoceanographer/WWF/blob/master/PCA_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [0]:
# Defines the path to load the relevant files
path = "gdrive/My Drive/GTL_PCA/"

Production

In [0]:
path_prod = path + "fao_production_2011_13.csv"
path_land = path + "pasture_crops.csv"

In [0]:
production_df = pd.read_csv(path_prod,index_col='Country')
land_df = pd.read_csv(path_land,index_col = 'ISO3')

In [13]:
land_df

                          crop_area_per_ISO3_hectare  ...  Unnamed: 10
ISO3                                                  ...
Afghanistan                             8.066484e+06  ...          NaN
Albania                                 6.423613e+05  ...          NaN
Algeria                                 5.582107e+06  ...          NaN
Angola                                  3.357759e+06  ...          NaN
NaN                                              NaN  ...          NaN
Argentina                               3.280245e+07  ...          NaN
Armenia                                 5.866188e+05  ...          NaN
Australia                               2.899305e+07  ...          NaN
Austria                                 1.496332e+06  ...          NaN
Azerbaijan                              1.982493e+06  ...          NaN
NaN                                              NaN  ...          NaN
Bangladesh                              8.282077e+06  ...          NaN
NaN                                              NaN  ...          NaN
Belarus                                 6.197959e+06  ...          NaN
Belgium                                 8.471679e+05  ...          NaN
Belize                                  1.055237e+05  ...          NaN
Benin                                   2.949974e+06  ...          NaN
NaN                                     0.000000e+00  ...          NaN
Bolivia                                 3.143956e+06  ...          NaN
Bosnia& Herzegovina                     1.136449e+06  ...          NaN
Botswana                                8.425333e+05  ...          NaN
Brazil                                  5.007777e+07  ...          NaN
Brunei                                  1.062730e+04  ...          NaN
Bulgaria                                3.642294e+06  ...          NaN
Burkina Faso                            4.383912e+06  ...          NaN
NaN                                              NaN  ...          NaN
Cambodia                                3.904576e+06  ...          NaN
Cameroon                                7.161297e+06  ...          NaN
Canada                                  4.148067e+07  ...          NaN
Central African Republic                2.050044e+06  ...          NaN
...                                              ...  ...          ...
Spain                                   1.821495e+07  ...          NaN
Sri Lanka                               1.843768e+06  ...          NaN
Sudan                                   1.721334e+07  ...          NaN
Suriname                                5.479383e+04  ...          NaN
Swaziland                               1.823052e+05  ...          NaN
Sweden                                  2.236204e+06  ...          NaN
Switzerland                             4.239014e+05  ...          NaN
Tajikistan                              1.019714e+06  ...          NaN
Thailand                                1.657281e+07  ...          NaN
NaN                                              NaN  ...          NaN
NaN                                              NaN  ...          NaN
Togo                                    2.306399e+06  ...          NaN
Trinidad & Tobago                       1.191022e+05  ...          NaN
Tunisia                                 2.332417e+06  ...          NaN
Turkey                                  2.166478e+07  ...          NaN
Turkmenistan                            1.868781e+06  ...          NaN
Uganda                                  8.182084e+06  ...          NaN
Ukraine                                 3.401068e+07  ...          NaN
United Arab Emirates                    1.576503e+05  ...          NaN
United Kingdom                          6.215838e+06  ...          NaN
Tanzania                                5.117023e+06  ...          NaN
USA                                     1.794152e+08  ...          NaN
Uruguay                                 1.436739e+06  ...          NaN
Uzbekistan                              5.235145e+06  ...  450855.4942
NaN                                              NaN  ...          NaN
Venezuela                               3.414763e+06  ...          NaN
Vietnam                                 6.935736e+06  ...          NaN
Yemen                                   1.461325e+06  ...          NaN
Zambia                                  5.263296e+06  ...          NaN
Zimbabwe                                3.367260e+06  ...          NaN

[170 rows x 10 columns]

In [18]:
# from Frank's code; averages the values
production_df["Value"].astype(int,inplace= True)
production_df["Year"].astype(int,inplace= True)
production_mean_df = production_df.pivot_table(index=['Country','Item'], 
                                      values=['Value'],
                                      aggfunc='mean', 
                                      fill_value=0) 

production_mean_df = production_mean_df.reset_index()

# Missing Values are filled with 0 
production_pivoted_df = production_mean_df.pivot_table(index='Country', columns = 'Item', values = 'Value', 
                                      fill_value=0) 

production_pivoted_df.head(5)

Item                 Barley and products  ...  Wheat and products
Country                                   ...
Afghanistan                   441.333333  ...         4535.666667
Albania                         7.666667  ...          295.666667
Algeria                      1398.333333  ...         3095.333333
Angola                          0.000000  ...            4.000000
Antigua and Barbuda             0.000000  ...            0.000000

[5 rows x 15 columns]

In [16]:
production_pivoted_df['Country'] land_df['Crop as Prop total']

KeyError: ignored